### ISSUE TITLE
SQL Table

### ISSUE THREAD

**Issue by zensabbah** [antonispa/Complete-Login-System-in-PHP#1]
Hi Anpapakadis nice job!

May you add the SQL for creating the table with correct field and name?

Kind Regards

**Comment by anpapadakis** [comment]
Hi @zensabbah!

I have uploaded the SQL script. You can find it here https://github.com/anpapadakis/Complete-Login-System-in-PHP/blob/master/sql/db_script.sql

Thank you!

**Comment by zensabbah** [comment]
Hi @anpapadakis , thanks a lot for your effort!
